/****** Object:  Table [dbo].[FLXY_RESERVATION_ITEM]    Script Date: 03/06/2022 2:34:36 PM ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FLXY_RESERVATION_ITEM]') AND type in (N'U'))
DROP TABLE [dbo].[FLXY_RESERVATION_ITEM]
GO

/****** Object:  Table [dbo].[FLXY_RESERVATION_ITEM]    Script Date: 03/06/2022 2:34:36 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FLXY_RESERVATION_ITEM](
	[RSV_PRI_ID] [int] IDENTITY(1,1) NOT NULL,
	[RSV_ID] [int] NULL,
	[RSV_ITM_ID] [nvarchar](255) NOT NULL,
	[RSV_ITM_CL_ID] [int] NULL,
	[RSV_ITM_BEGIN_DATE] [nvarchar](255) NULL,
	[RSV_ITM_END_DATE] [nvarchar](255) NULL,
	[RSV_ITM_BEGIN_TIME] [nvarchar](255) NULL,
	[RSV_ITM_END_END_TIME] [nvarchar](255) NULL,
	[RSV_ITM_QTY] [nvarchar](255) NOT NULL,
	[RSV_ITM_STATUS] [tinyint] NULL,
 CONSTRAINT [PK_FLXY_RESERVATION_ITEM] PRIMARY KEY CLUSTERED 
(
	[RSV_PRI_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
